spring.application.name=royal-airlines

spring.mongodb.uri=${DB_URI}
spring.mongodb.database=${DB_DATABASE}
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_OAUTH_CLIENT}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_OAUTH_SECRET}
spring.ai.ollama.base-url=${CHAT_MODEL_URI}
spring.ai.ollama.chat.model=${CHAT_MODEL}